[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "nix"
language-servers = ["nixd"]
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true

[[language]]
name = "jsonc"
language-servers = ["vscode-json-language-server"]
auto-format = true
